# Site settings
title: relatos
SEOTitle: relatos|一个分享故事的地方
header-img: img/home-bg.jpg
email: relatos@126.com
description: "relatos | 荒蛮故事 | 个人传记 | 奇思妙想 | 深度思考"
keyword: "relatos, 故事,你知道的"
url: "https://relatos.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
timezone: CN


# SNS settings
RSS: false
#weibo_username:     relatos
#zhihu_username:     relatos
github_username:    relatos
#twitter_username:  huxpro
#facebook_username:  relatos
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: ityouknow
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: d301c1a24ccfbed1a5d2dde44076cd20
# Google Analytics
ga_track_id: 'UA-81503915-1'            # Format: UA-xxxxxx-xx
ga_domain: relatos.top



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "This Corner World"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
# friends: [
#     {
#         title: "Su",
#         href: "http://su.gallery/"
#     },{
#         title: "乱序",
#         href: "http://mida.re/"
#     }
# ]
